In [2]:
import pandas as pd
import sqlite3
from tqdm.notebook import tqdm
import numpy as np

In [43]:
vandy_recs = pd.read_csv('data/prov_org_vandy_perc.csv')

In [44]:
vandy_recs

,Unnamed: 0,prov_zip,prov_spec,org_spec,non_vandy_transactions,vandy_transactions,perc_vandy
0,0,37013,Chiropractor,Chiropractor,185,0.0,0.0
1,1,37013,Clinic/Center(Primary Care),Emergency Medicine,59,0.0,0.0
2,2,37013,Clinic/Center(Primary Care),General Acute Care Hospital,59,0.0,0.0
3,3,37013,Clinic/Center(Primary Care),Internal Medicine,300,0.0,0.0
4,4,37013,Clinic/Center(Primary Care),Psychiatric Hospital,286,0.0,0.0
...,...,...,...,...,...,...,...
10895,12170,38563,Nurse Practitioner(Women's Health),Nurse Practitioner(Family),1309,0.0,0.0
10896,12171,38563,Nurse Practitioner(Women's Health),Pharmacy(Community/Retail Pharmacy),80,0.0,0.0
10897,12172,38563,Nurse Practitioner(Women's Health),Radiology(Diagnostic Radiology),213,0.0,0.0
10898,12173,38563,Physical Therapist,Clinical Medical Laboratory,71,0.0,0.0
10899,12174,38563,Physical Therapist,Physical Therapist,589,0.0,0.0

In [45]:
vandy_recs['total'] = vandy_recs['non_vandy_transactions'] + vandy_recs['vandy_transactions']
vandy_recs=vandy_recs.drop(columns='Unnamed: 0')
vandy_recs

,prov_zip,prov_spec,org_spec,non_vandy_transactions,vandy_transactions,perc_vandy,total
0,37013,Chiropractor,Chiropractor,185,0.0,0.0,185.0
1,37013,Clinic/Center(Primary Care),Emergency Medicine,59,0.0,0.0,59.0
2,37013,Clinic/Center(Primary Care),General Acute Care Hospital,59,0.0,0.0,59.0
3,37013,Clinic/Center(Primary Care),Internal Medicine,300,0.0,0.0,300.0
4,37013,Clinic/Center(Primary Care),Psychiatric Hospital,286,0.0,0.0,286.0
...,...,...,...,...,...,...,...
10895,38563,Nurse Practitioner(Women's Health),Nurse Practitioner(Family),1309,0.0,0.0,1309.0
10896,38563,Nurse Practitioner(Women's Health),Pharmacy(Community/Retail Pharmacy),80,0.0,0.0,80.0
10897,38563,Nurse Practitioner(Women's Health),Radiology(Diagnostic Radiology),213,0.0,0.0,213.0
10898,38563,Physical Therapist,Clinical Medical Laboratory,71,0.0,0.0,71.0
10899,38563,Physical Therapist,Physical Therapist,589,0.0,0.0,589.0

In [24]:
hop_proj=sqlite3.connect('data/hop_proj.sqlite')

query = """
SELECT DISTINCT class_spec
FROM taxonomy
JOIN nppes
ON code = primary_taxonomy
WHERE org_name LIKE '%vanderbilt%'
    
"""

vandy_specs = pd.read_sql(query, hop_proj)

vandy_specs

                                           class_spec
0                                Allergy & Immunology
1                                     Family Medicine
2                                   Internal Medicine
3        Internal Medicine(Interventional Cardiology)
4                     Radiology(Diagnostic Radiology)
5                       Radiology(Radiation Oncology)
6                                             Surgery
7                            Counselor(Mental Health)
8                                        Psychologist
9                             Social Worker(Clinical)
10                                       Chiropractor
11                              Dietitian, Registered
12                                        Optometrist
13                              Genetic Counselor, MS
14                          Advanced Practice Midwife
15            Nurse Anesthetist, Certified Registered
16         Nurse Practitioner(Critical Care Medicine)
17                     Nurse Practitioner(Pediatrics)
18                             Occupational Therapist
19                     Physical Therapist(Orthopedic)
20          Specialist/Technologist(Athletic Trainer)
21                                        Home Health
22                                      Clinic/Center
23                            Clinic/Center(Birthing)
24  Clinic/Center(End-Stage Renal Disease (ESRD) T...
25                      Clinic/Center(Health Service)
26  Clinic/Center(Mental Health (Including Communi...
27                 Clinic/Center(Oncology, Radiation)
28                           Clinic/Center(Radiology)
29                        Clinic/Center(Rural Health)
30                    Medicare Defined Swing Bed Unit
31                                   Psychiatric Unit
32                                Rehabilitation Unit
33                        General Acute Care Hospital
34              General Acute Care Hospital(Children)
35       General Acute Care Hospital(Critical Access)
36                               Psychiatric Hospital
37                            Rehabilitation Hospital
38                           Assisted Living Facility
39                           Skilled Nursing Facility
40       Durable Medical Equipment & Medical Supplies
41                                   Eyewear Supplier
42                       Non-Pharmacy Dispensing Site
43                                           Pharmacy
44                Pharmacy(Community/Retail Pharmacy)
45                   Pharmacy(Institutional Pharmacy)
46                       Pharmacy(Specialty Pharmacy)

In [56]:
vandy_services = vandy_specs['class_spec'].tolist()

vandy = vandy_recs.columns
vandy_df = pd.DataFrame(columns = vandy)
for i in vandy_services:
    result = vandy_recs[vandy_recs['org_spec'] == i]
    vandy_df = vandy_df.append(result)

In [57]:
vandy_df.sort_values(by = 'org_spec')

,prov_zip,prov_spec,org_spec,non_vandy_transactions,vandy_transactions,perc_vandy,total
3320,37083,Nurse Practitioner(Family),Assisted Living Facility,87,0.0,0.0,87.0
628,37043,Nurse Practitioner,Assisted Living Facility,128,0.0,0.0,128.0
2352,37075,Family Medicine(Geriatric Medicine),Assisted Living Facility,222,0.0,0.0,222.0
2646,37075,Nurse Practitioner(Gerontology),Assisted Living Facility,53,0.0,0.0,53.0
6161,37186,Physician Assistant,Assisted Living Facility,53,0.0,0.0,53.0
...,...,...,...,...,...,...,...
6435,37203,Hospitalist,Skilled Nursing Facility,68,0.0,0.0,68.0
6416,37203,General Practice,Skilled Nursing Facility,1440,0.0,0.0,1440.0
7558,37205,Internal Medicine,Skilled Nursing Facility,1160,0.0,0.0,1160.0
1317,37066,Internal Medicine(Cardiovascular Disease),Skilled Nursing Facility,106,0.0,0.0,106.0
1598,37066,Social Worker(Clinical),Social Worker(Clinical),122,0.0,0.0,122.0

In [63]:
vandy_df.pivot_table(values='total', index=['prov_zip', 'org_spec'], aggfunc=np.sum, fill_value=0).reset_index()

     prov_zip                                           org_spec  total
0       37013                                       Chiropractor    185
1       37013  Clinic/Center(Mental Health (Including Communi...    204
2       37013                                    Family Medicine    777
3       37013                        General Acute Care Hospital   3444
4       37013                                  Internal Medicine  10119
..        ...                                                ...    ...
694     38563                        General Acute Care Hospital     56
695     38563       General Acute Care Hospital(Critical Access)    846
696     38563                                  Internal Medicine    552
697     38563                Pharmacy(Community/Retail Pharmacy)     80
698     38563                    Radiology(Diagnostic Radiology)    471

[699 rows x 3 columns]